sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: '4'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install: .travis/script-before-install.sh
before_script: .travis/script-before.sh
script: .travis/script-build.sh
after_success: .travis/script-after-success.sh
addons:
  sauce_connect:
    username: patrinhani-ciandt
    access_key: "e7560d31-b7b9-4108-abad-12b4124e9edc"
branches:
  except:
    - gh-pages
    - /^v?\d+\.\d+\.\d+$/