sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: '4'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm install
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
  - polylint
script:
  - xvfb-run wct
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
addons:
  sauce_connect:
    username: "patrinhani-ciandt"
    access_key: "e7560d31-b7b9-4108-abad-12b4124e9edc"
after_success:
  - npm run semantic-release
branches:
  except: 
    - gh-pages
    - /^v\d+\.\d+\.\d+$/
